version: '3.4'
services:

  'nginx.internal.mos-sigma.com':
    container_name: nginx
    build:
      context: '..'
      dockerfile: .devcontainer/nginx/Dockerfile
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - ../:/var/www/app:delegated
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  'redis.internal.mos-sigma.com':
    container_name: redis
    image: bitnami/redis:5.0
    ports:
        - '6379:6379'
    environment:
      - REDIS_PASSWORD=na8!^&*JbXEz

  'fpm.internal.mos-sigma.com':
    container_name: fpm
    build:
      context: '..'
      dockerfile: .docker/Dockerfile
      target: development
    volumes:
        - ../:/var/www/app:delegated
    depends_on:
      - 'redis.internal.mos-sigma.com'

  'echo.internal.mos-sigma.com':
    container_name: echo
    build:
      context: '.'
      dockerfile: echo/Dockerfile
    ports:
        - '6001:6001'

  'devtools.internal.mos-sigma.com':
    container_name: devtools
    build: "./devtools"
    volumes:
        - ../:/var/www/app:delegated
    ports:
        - '35729:35729'

  'db.internal.mos-sigma.com':
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
