version: '3.4'
services:

  app:
    container_name: app
    build:
      context: '..'
    dns:
     - 1.1.1.1 # Cloudflare
     - 8.8.8.8 # Google
    extra_hosts:
     - "proxy.localhost:127.0.0.1"
    ports:
        - '35729:35729' # Live reload port
        - '8080:8080'
    volumes:
        - ../:/var/www/app:delegated
        - ~/.composer:/root/.composer
        - ~/.npm:/root/.npm
    depends_on:
      - redis
      - db
    command:  /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: redis
    image: bitnami/redis:5.0
    ports:
        - '6379:6379'
    environment:
      - REDIS_PASSWORD=na8!^&*JbXEz
    volumes:
      - redis:/data

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
        - '9200:9200'
    environment:
          - node.name=sigmie-es
          - cluster.name=sigmie-dev
          #- discovery.seed_hosts=es02,es03
          - cluster.initial_master_nodes=sigmie-es
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data

volumes:
  db:
  redis:
  es:
