version: '3.4'
services:

  app:
    container_name: app
    build:
      context: '..'
    ports:
        - '35729:35729' # Live reload port
        - '8080:8080'
    volumes:
        - ../:/var/www/app:delegated
        - ~/.composer:/root/.composer
        - ~/.npm:/root/.npm
    depends_on:
      - redis
      - db
    command:  /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: redis
    image: bitnami/redis:5.0
    ports:
        - '6379:6379'
    environment:
      - REDIS_PASSWORD=na8!^&*JbXEz
    volumes:
      - redis:/data

volumes:
  db:
  redis:
