version: '3'
services:
  nginx:
    build: "./nginx"
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - code:/var/www/app:nocopy
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php-fpm
    build: "./php-fpm"
    volumes:
        - code:/var/www/app:nocopy
  devtools:
    container_name: devtools
    build: "./devtools"
    volumes:
        - code:/var/www/app:nocopy
    ports:
        - '35729:35729'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  code:
    external: true
