version: '3'
services:
  web:
    image: nginx:1.17
    ports:
        - '80:80'
    volumes:
        - epsiloncode-rsync-sync:/var/www/app:nocopy
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php-fpm
    build: "./php-fpm"
    volumes:
        - epsiloncode-rsync-sync:/var/www/app:nocopy
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  epsiloncode-rsync-sync:
    external: true
