name: Deploy

on:
 release:
    types:
      - created

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Deploy
      run: echo 'Deploy application'

    # gcloud compute instances delete-access-config $VM_NAME --access-config-name "External NAT"
    # gcloud compute instances add-access-config $VM_NAME --access-config-name "External NAT" --address $IP
