name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GOOGLE_PASSPHRASE: ${{ secrets.google_passphrase }}
      COMPOSER_PASSPHRASE: ${{ secrets.composer_passphrase }}
      DB_HOST: 127.0.0.1
      DB_PORT: 3307
      DB_DATABASE: mos-sigma
      DB_USERNAME: root
      DB_PASSWORD: zed6u8C2U4*$
      # DB_USERNAME: app
      # DB_PASSWORD: u#Rh2!HTr2HA
    steps:
    - uses: actions/checkout@v2

    - name: Set tag env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

    - name: Set assets env
      run: echo ::set-env name=ASSETS_HASH::$(md5sum ./public/mix-manifest.json | awk '{ print $1 }')

    - name: Decrypt google secret
      run: gpg --quiet --batch --yes --decrypt --passphrase=$GOOGLE_PASSPHRASE --output google.json .github/secrets/google.json.gpg

    - name: Decrypt composer secret
      run: gpg --quiet --batch --yes --decrypt --passphrase=$COMPOSER_PASSPHRASE --output auth.json .github/secrets/composer.json.gpg

    - name: Start sql proxy
      run: docker run -d -v google.json:/config -p 3307:3306 gcr.io/cloudsql-docker/gce-proxy:1.16 /cloud_sql_proxy -instances=mossigma-app-production:europe-west1:mos-sigma=tcp:0.0.0.0:3306 -credential_file=/config

    - name: Install curl and npm
      run: sudo apt-get update && sudo apt-get install -y curl npm

    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install php production dependencies
      run: composer install -q --no-dev --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Migrate database
      run: php artisan migrate --force

    - name: Install node dependencies
      run:  curl https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.gz | sudo tar xzvf - --exclude CHANGELOG.md --exclude LICENSE --exclude README.md --strip-components 1 -C /usr/local/

    - name: Install node
      run: npm install

    - name: Create .env file
      run: |
        echo "APP_NAME=MOS-Sigma"                                                                  >> .env
        echo "APP_ENV=production"                                                                  >> .env
        echo "APP_KEY=base64:6CPMmM8RByBPlknSQqcwHQ86a1SO+ZEa9/zeGKqj974="                         >> .env
        echo "APP_DEBUG=true"                                                                      >> .env
        echo "APP_URL=https://mos-sigma.com"                                                       >> .env
        echo ""                                                                                    >> .env
        echo "LOG_CHANNEL=stack"                                                                   >> .env
        echo ""                                                                                    >> .env
        echo "DB_CONNECTION=mysql"                                                                 >> .env
        echo "DB_HOST=sqlproxy.internal.mos-sigma.com"                                             >> .env
        echo "DB_PORT=3306"                                                                        >> .env
        echo "DB_DATABASE=mos-sigma"                                                               >> .env
        echo "DB_USERNAME=app"                                                                     >> .env
        echo "DB_PASSWORD=u#Rh2!HTr2HA"                                                            >> .env
        echo ""                                                                                    >> .env
        echo "BROADCAST_DRIVER=redis"                                                              >> .env
        echo ""                                                                                    >> .env
        echo "CACHE_DRIVER=redis"                                                                  >> .env
        echo ""                                                                                    >> .env
        echo "QUEUE_CONNECTION=redis"                                                              >> .env
        echo ""                                                                                    >> .env
        echo "SESSION_DRIVER=redis"                                                                >> .env
        echo "SESSION_LIFETIME=120"                                                                >> .env
        echo ""                                                                                    >> .env
        echo "ASSET_URL=https://mos-sigma.storage.googleapis.com/4550dc497a3e7d28f5a01ea02f68a8df" >> .env
        echo ""                                                                                    >> .env
        echo "TELESCOPE_ENABLED=true" >> .env

    - name: Clear and cache routes
      run: php artisan route:clear && php artisan route:cache

    - name: Clear and cache config
      run: php artisan config:clear && php artisan config:cache

    - name: Compile production assets
      run: npm run production

    - name: Install GCloud
      run: if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi

    - name: Gcloud authentication
      run: gcloud auth activate-service-account --key-file=google.json

    - name: Docker authentication
      run: gcloud auth configure-docker

    - name: Deploy assets to mos-sigma bucket
      run: gsutil -m rsync -r ./public gs://mos-sigma/${ASSETS_HASH}

    - name: Echo assets url to .env
      run: echo "ASSET_URL=https://mos-sigma.storage.googleapis.com/${ASSETS_HASH}"

    - name: Build nginx image
      run: docker build -t eu.gcr.io/mossigma-app-production/nginx -f .devcontainer/nginx/Dockerfile .

    - name: Push nginx image to gcr
      run: docker push eu.gcr.io/mossigma-app-production/nginx

    - name: Build php image
      run: docker build -t eu.gcr.io/mossigma-app-production/fpm -f .devcontainer/fpm/Dockerfile .

    - name: Push php image to gcr
      run: docker push eu.gcr.io/mossigma-app-production/fpm

    - name: Build sheduler image
      run: docker build -t eu.gcr.io/mossigma-app-production/scheduler -f .devcontainer/scheduler/Dockerfile .

    - name: Push sheduler image to gcr
      run: docker push eu.gcr.io/mossigma-app-production/scheduler

    - name: Build worker image
      run: docker build -t eu.gcr.io/mossigma-app-production/worker -f .devcontainer/worker/Dockerfile .

    - name: Push worker image to gcr
      run: docker push eu.gcr.io/mossigma-app-production/worker

