name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      COMPOSER_PASSPHRASE: ${{ secrets.composer_passphrase }}

    steps:
    - uses: actions/checkout@v2

    - name: Set release version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

    - name: Decrypt composer secret
      run: gpg --quiet --batch --yes --decrypt --passphrase=$COMPOSER_PASSPHRASE --output auth.json .github/secrets/composer.json.gpg

    - name: Install curl npm zip
      run: sudo apt-get update && sudo apt-get install -y curl npm zip

    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Install node
      run:  curl https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.gz | sudo tar xzvf - --exclude CHANGELOG.md --exclude LICENSE --exclude README.md --strip-components 1 -C /usr/local/

    - name: Validate composer and install prod dependecies
      run: composer install -q --no-dev --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Install node and generate production assets
      run: npm install && npm run production

    - name: Build image
      run: docker build -t docker.pkg.github.com/nicoorfi/mos-sigma/mos-sigma:${RELEASE_VERSION} -f .docker/fpm/Dockerfile .

    - name: Authenticate docker
      run: docker login docker.pkg.github.com --username nicoorfi --password ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: docker push docker.pkg.github.com/nicoorfi/mos-sigma/mos-sigma:${RELEASE_VERSION}
