name: split

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Split Sigmie

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Authenticate Github
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Split code 
        run: bin/split.sh
