name: Style

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: PHPStan
      run: vendor/bin/phpstan analyse --level 8 app


    - name: PHPCS
      run: vendor/bin/phpcs --standard=standard.xml ./app
