name: Code style

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      GOOGLE_PASSPHRASE: ${{ secrets.google_passphrase }}
      COMPOSER_PASSPHRASE: ${{ secrets.composer_passphrase }}

    steps:
    - uses: actions/checkout@v2

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl npm zip

    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Decrypt google and composer secrets
      run: |
          gpg --quiet --batch --yes --decrypt --passphrase=$COMPOSER_PASSPHRASE --output auth.json .github/secrets/composer.json.gpg

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install php dependencies
      run: composer install -q --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Install node dependencies
      run:  curl https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.gz | sudo tar xzvf - --exclude CHANGELOG.md --exclude LICENSE --exclude README.md --strip-components 1 -C /usr/local/

    - name: Install node
      run: npm install

    - name: PHPStan
      run: vendor/bin/phpstan analyse --level 8 app

    - name: PHPCS
      run: vendor/bin/phpcs --standard=standard.xml ./app

    - name: JS Standard
      run: node_modules/standard/bin/cmd.js | node_modules/snazzy/bin/cmd.js
