name: Code style

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-18.04
    if: github.ref != 'refs/heads/master'

    env:
      COMPOSER_PASSPHRASE: ${{ secrets.composer_passphrase }}
      SLACK_HOOK_URL: ${{ secrets.slack_webhook_url }}

    steps:
    - uses: actions/checkout@v2

    - name: Slack notification
      run: |
           curl -X POST --data-urlencode 'payload={"channel": "#cicd", "text": "Code style workflow has started."}' $SLACK_HOOK_URL

    - name: Cache node modules
      uses: actions/cache@v1
      with:
       path: ~/.npm
       key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
       path: ~/.composer
       key: composer-${{ hashFiles('**/composer.lock') }}

    - name: Install curl zip
      run: sudo apt-get update && sudo apt-get install -y curl zip

    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Decrypt composer secret
      run: gpg --quiet --batch --yes --decrypt --passphrase=$COMPOSER_PASSPHRASE --output auth.json .github/secrets/auth.json.gpg

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install php dependencies
      run: composer install

    - uses: borales/actions-yarn@v2.0.0
      with:
       cmd: install

    - uses: borales/actions-yarn@v2.0.0
      with:
       cmd: prod

    - name: PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=-1

    - name: PHPCS
      run: vendor/bin/phpcs --standard=phpcs-laravel app

    - name: JS Standard
      run: node_modules/standard/bin/cmd.js | node_modules/snazzy/bin/cmd.js

    - name: Slack finish notification
      run: |
           curl -X POST --data-urlencode 'payload={"channel": "#cicd", "text": "Code style checks have passed."}' $SLACK_HOOK_URL
