name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04
    services:
     mysql:
      image: mysql:5.7
      ports:
        - 3307:3306
      env:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
     redis:
      image: bitnami/redis:latest
      ports:
        - 6379:6379
      env:
        REDIS_PASSWORD: password
    env:
      COMPOSER_PASSPHRASE: ${{ secrets.composer_passphrase }}

    steps:
    - uses: actions/checkout@v2

    - name: Decrypt google and composer secrets
      run: gpg --quiet --batch --yes --decrypt --passphrase=$COMPOSER_PASSPHRASE --output auth.json .github/secrets/composer.json.gpg

    - name: Install curl and npm
      run: sudo apt-get update && sudo apt-get install -y curl npm zip

    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Validate composer and install prod dependecies
      run: composer validate && composer install -q --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Install node dependencies
      run:  curl https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.gz | sudo tar xzvf - --exclude CHANGELOG.md --exclude LICENSE --exclude README.md --strip-components 1 -C /usr/local/

    - name: Install node and generate production assets
      run: npm install && npm run production

    - name: Create .env file
      run: |
        echo "APP_NAME=MOS-Sigma"                                                                  >> .env
        echo "APP_ENV=production"                                                                  >> .env
        echo "APP_KEY=base64:6CPMmM8RByBPlknSQqcwHQ86a1SO+ZEa9/zeGKqj974="                         >> .env
        echo "APP_DEBUG=false"                                                                     >> .env
        echo "APP_URL=https://mos-sigma.com"                                                       >> .env
        echo ""                                                                                    >> .env
        echo "LOG_CHANNEL=stack"                                                                   >> .env
        echo ""                                                                                    >> .env
        echo "DB_CONNECTION=mysql"                                                                 >> .env
        echo "DB_HOST=127.0.0.1"                                                                       >> .env
        echo "DB_PORT=3307"                                                                        >> .env
        echo "DB_DATABASE=db"                                                                      >> .env
        echo "DB_USERNAME=user"                                                                    >> .env
        echo "DB_PASSWORD=password"                                                                >> .env
        echo ""                                                                                    >> .env
        echo "BROADCAST_DRIVER=redis"                                                              >> .env
        echo ""                                                                                    >> .env
        echo "CACHE_DRIVER=redis"                                                                  >> .env
        echo ""                                                                                    >> .env
        echo "REDIS_HOST=localhost"                                                                >> .env
        echo "REDIS_PASSWORD=password"                                                             >> .env
        echo "REDIS_PORT=6379"                                                                     >> .env
        echo ""                                                                                    >> .env
        echo "QUEUE_CONNECTION=redis"                                                              >> .env
        echo ""                                                                                    >> .env
        echo "SESSION_DRIVER=redis"                                                                >> .env
        echo "SESSION_LIFETIME=120"                                                                >> .env
        echo ""                                                                                    >> .env
        echo "TELESCOPE_ENABLED=true"                                                              >> .env
        echo "ASSET_URL=https://mos-sigma.storage.googleapis.com/${ASSETS_HASH}"                   >> .env

    - name: Phpunit
      run: vendor/bin/phpunit

    - name: Migrations
      run: php artisan migrate --force
